version: "3.9"
services:

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx

    env_file: ../../.env

    ports:
      - "443:443"

    volumes:
      - "./system/services/nginx/templates:/etc/nginx/templates"
      - "./system/services/nginx/certbot/letsencrypt:/etc/letsencrypt"
      - "./system/services/nginx/certbot/html:/var/www/certbot"

  open_position:
    env_file: ../../.env
    build:
      context: "../../src/services"
      dockerfile: "../../system/services/open_position/Dockerfile"

    container_name: open_position

    restart: unless-stopped

  db:
    env_file: ../../.env
    build:
      context: "../../src/services"
      dockerfile: "../../system/services/db/Dockerfile"

    container_name: db

    restart: unless-stopped